import "./globals.css";

export const metadata = {
  title: "adcosta's Next App",
  description: "Generated by adcosta apps",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
