name: CI
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-team13:
    uses: ./.github/workflows/test copy error cache.yaml
    secrets: inherit
